"""AUTO-GENERATED by scripts/gen_countries.py -- do not edit by hand.

Country reference data for the hard location filter and geo-targeting.
Regenerate with:  venv/Scripts/python scripts/gen_countries.py
"""

CC_DISPLAY = {
"ad": "Andorra",
"ae": "United Arab Emirates",
"af": "Afghanistan",
"ag": "Antigua and Barbuda",
"ai": "Anguilla",
"al": "Albania",
"am": "Armenia",
"an": "Netherlands Antilles",
"ao": "Angola",
"aq": "Antarctica",
"ar": "Argentina",
"as": "American Samoa",
"at": "Austria",
"au": "Australia",
"aw": "Aruba",
"ax": "Aland Islands",
"az": "Azerbaijan",
"ba": "Bosnia and Herzegovina",
"bb": "Barbados",
"bd": "Bangladesh",
"be": "Belgium",
"bf": "Burkina Faso",
"bg": "Bulgaria",
"bh": "Bahrain",
"bi": "Burundi",
"bj": "Benin",
"bl": "Saint Barthelemy",
"bm": "Bermuda",
"bn": "Brunei",
"bo": "Bolivia",
"bq": "Bonaire, Saint Eustatius and Saba ",
"br": "Brazil",
"bs": "Bahamas",
"bt": "Bhutan",
"bv": "Bouvet Island",
"bw": "Botswana",
"by": "Belarus",
"bz": "Belize",
"ca": "Canada",
"cc": "Cocos Islands",
"cd": "Democratic Republic of the Congo",
"cf": "Central African Republic",
"cg": "Republic of the Congo",
"ch": "Switzerland",
"ci": "Ivory Coast",
"ck": "Cook Islands",
"cl": "Chile",
"cm": "Cameroon",
"cn": "China",
"co": "Colombia",
"cr": "Costa Rica",
"cs": "Serbia and Montenegro",
"cu": "Cuba",
"cv": "Cabo Verde",
"cw": "Curacao",
"cx": "Christmas Island",
"cy": "Cyprus",
"cz": "Czechia",
"de": "Germany",
"dj": "Djibouti",
"dk": "Denmark",
"dm": "Dominica",
"do": "Dominican Republic",
"dz": "Algeria",
"ec": "Ecuador",
"ee": "Estonia",
"eg": "Egypt",
"eh": "Western Sahara",
"er": "Eritrea",
"es": "Spain",
"et": "Ethiopia",
"fi": "Finland",
"fj": "Fiji",
"fk": "Falkland Islands",
"fm": "Micronesia",
"fo": "Faroe Islands",
"fr": "France",
"ga": "Gabon",
"gb": "United Kingdom",
"gd": "Grenada",
"ge": "Georgia",
"gf": "French Guiana",
"gg": "Guernsey",
"gh": "Ghana",
"gi": "Gibraltar",
"gl": "Greenland",
"gm": "Gambia",
"gn": "Guinea",
"gp": "Guadeloupe",
"gq": "Equatorial Guinea",
"gr": "Greece",
"gs": "South Georgia and the South Sandwich Islands",
"gt": "Guatemala",
"gu": "Guam",
"gw": "Guinea-Bissau",
"gy": "Guyana",
"hk": "Hong Kong",
"hm": "Heard Island and McDonald Islands",
"hn": "Honduras",
"hr": "Croatia",
"ht": "Haiti",
"hu": "Hungary",
"id": "Indonesia",
"ie": "Ireland",
"il": "Israel",
"im": "Isle of Man",
"in": "India",
"io": "British Indian Ocean Territory",
"iq": "Iraq",
"ir": "Iran",
"is": "Iceland",
"it": "Italy",
"je": "Jersey",
"jm": "Jamaica",
"jo": "Jordan",
"jp": "Japan",
"ke": "Kenya",
"kg": "Kyrgyzstan",
"kh": "Cambodia",
"ki": "Kiribati",
"km": "Comoros",
"kn": "Saint Kitts and Nevis",
"kp": "North Korea",
"kr": "South Korea",
"kw": "Kuwait",
"ky": "Cayman Islands",
"kz": "Kazakhstan",
"la": "Laos",
"lb": "Lebanon",
"lc": "Saint Lucia",
"li": "Liechtenstein",
"lk": "Sri Lanka",
"lr": "Liberia",
"ls": "Lesotho",
"lt": "Lithuania",
"lu": "Luxembourg",
"lv": "Latvia",
"ly": "Libya",
"ma": "Morocco",
"mc": "Monaco",
"md": "Moldova",
"me": "Montenegro",
"mf": "Saint Martin",
"mg": "Madagascar",
"mh": "Marshall Islands",
"mk": "North Macedonia",
"ml": "Mali",
"mm": "Myanmar",
"mn": "Mongolia",
"mo": "Macao",
"mp": "Northern Mariana Islands",
"mq": "Martinique",
"mr": "Mauritania",
"ms": "Montserrat",
"mt": "Malta",
"mu": "Mauritius",
"mv": "Maldives",
"mw": "Malawi",
"mx": "Mexico",
"my": "Malaysia",
"mz": "Mozambique",
"na": "Namibia",
"nc": "New Caledonia",
"ne": "Niger",
"nf": "Norfolk Island",
"ng": "Nigeria",
"ni": "Nicaragua",
"nl": "The Netherlands",
"no": "Norway",
"np": "Nepal",
"nr": "Nauru",
"nu": "Niue",
"nz": "New Zealand",
"om": "Oman",
"pa": "Panama",
"pe": "Peru",
"pf": "French Polynesia",
"pg": "Papua New Guinea",
"ph": "Philippines",
"pk": "Pakistan",
"pl": "Poland",
"pm": "Saint Pierre and Miquelon",
"pn": "Pitcairn",
"pr": "Puerto Rico",
"ps": "Palestinian Territory",
"pt": "Portugal",
"pw": "Palau",
"py": "Paraguay",
"qa": "Qatar",
"re": "Reunion",
"ro": "Romania",
"rs": "Serbia",
"ru": "Russia",
"rw": "Rwanda",
"sa": "Saudi Arabia",
"sb": "Solomon Islands",
"sc": "Seychelles",
"sd": "Sudan",
"se": "Sweden",
"sg": "Singapore",
"sh": "Saint Helena",
"si": "Slovenia",
"sj": "Svalbard and Jan Mayen",
"sk": "Slovakia",
"sl": "Sierra Leone",
"sm": "San Marino",
"sn": "Senegal",
"so": "Somalia",
"sr": "Suriname",
"ss": "South Sudan",
"st": "Sao Tome and Principe",
"sv": "El Salvador",
"sx": "Sint Maarten",
"sy": "Syria",
"sz": "Eswatini",
"tc": "Turks and Caicos Islands",
"td": "Chad",
"tf": "French Southern Territories",
"tg": "Togo",
"th": "Thailand",
"tj": "Tajikistan",
"tk": "Tokelau",
"tl": "Timor Leste",
"tm": "Turkmenistan",
"tn": "Tunisia",
"to": "Tonga",
"tr": "Turkey",
"tt": "Trinidad and Tobago",
"tv": "Tuvalu",
"tw": "Taiwan",
"tz": "Tanzania",
"ua": "Ukraine",
"ug": "Uganda",
"um": "United States Minor Outlying Islands",
"us": "United States",
"uy": "Uruguay",
"uz": "Uzbekistan",
"va": "Vatican",
"vc": "Saint Vincent and the Grenadines",
"ve": "Venezuela",
"vg": "British Virgin Islands",
"vi": "U.S. Virgin Islands",
"vn": "Vietnam",
"vu": "Vanuatu",
"wf": "Wallis and Futuna",
"ws": "Samoa",
"xk": "Kosovo",
"ye": "Yemen",
"yt": "Mayotte",
"za": "South Africa",
"zm": "Zambia",
"zw": "Zimbabwe"
}

COUNTRY_NAME_TOKENS = {
"ad": [
"andorra",
"andorra la vella",
"principality of andorra"
],
"ae": [
"abu dhabi",
"u.a.e.",
"uae",
"united arab emirates"
],
"af": [
"afghanistan",
"islamic republic of afghanistan",
"kabul"
],
"ag": [
"antigua and barbuda",
"st. john's"
],
"ai": [
"anguilla",
"the valley"
],
"al": [
"albania",
"republic of albania",
"tirana"
],
"am": [
"armenia",
"republic of armenia",
"yerevan"
],
"an": [
"netherlands antilles",
"willemstad"
],
"ao": [
"angola",
"luanda",
"republic of angola"
],
"aq": [
"antarctica"
],
"ar": [
"argentina",
"argentine republic",
"buenos aires"
],
"as": [
"american samoa",
"pago pago"
],
"at": [
"austria",
"republic of austria",
"vienna"
],
"au": [
"australia",
"canberra"
],
"aw": [
"aruba",
"oranjestad"
],
"ax": [
"aland islands",
"mariehamn"
],
"az": [
"azerbaijan",
"baku",
"republic of azerbaijan"
],
"ba": [
"bosnia and herzegovina",
"republic of bosnia and herzegovina",
"sarajevo"
],
"bb": [
"barbados",
"bridgetown"
],
"bd": [
"bangladesh",
"dhaka",
"people's republic of bangladesh"
],
"be": [
"belgium",
"brussels",
"kingdom of belgium"
],
"bf": [
"burkina faso",
"ouagadougou"
],
"bg": [
"bulgaria",
"republic of bulgaria",
"sofia"
],
"bh": [
"bahrain",
"kingdom of bahrain",
"manama"
],
"bi": [
"burundi",
"gitega",
"republic of burundi"
],
"bj": [
"benin",
"porto-novo",
"republic of benin"
],
"bl": [
"gustavia",
"saint barthelemy"
],
"bm": [
"bermuda",
"hamilton"
],
"bn": [
"bandar seri begawan",
"brunei",
"brunei darussalam"
],
"bo": [
"bolivia",
"bolivia, plurinational state of",
"plurinational state of bolivia",
"sucre"
],
"bq": [
"bonaire, saint eustatius and saba",
"bonaire, sint eustatius and saba"
],
"br": [
"brasilia",
"brazil",
"federative republic of brazil"
],
"bs": [
"bahamas",
"commonwealth of the bahamas",
"nassau"
],
"bt": [
"bhutan",
"kingdom of bhutan",
"thimphu"
],
"bv": [
"bouvet island"
],
"bw": [
"botswana",
"gaborone",
"republic of botswana"
],
"by": [
"belarus",
"minsk",
"republic of belarus"
],
"bz": [
"belize",
"belmopan"
],
"ca": [
"canada",
"ottawa"
],
"cc": [
"cocos (keeling) islands",
"cocos islands",
"west island"
],
"cd": [
"congo, the democratic republic of the",
"democratic republic of the congo",
"kinshasa"
],
"cf": [
"bangui",
"central african republic"
],
"cg": [
"brazzaville",
"congo",
"republic of the congo"
],
"ch": [
"bern",
"swiss confederation",
"switzerland"
],
"ci": [
"cote d'ivoire",
"ivory coast",
"republic of cote d'ivoire",
"yamoussoukro"
],
"ck": [
"avarua",
"cook islands"
],
"cl": [
"chile",
"republic of chile",
"santiago"
],
"cm": [
"cameroon",
"republic of cameroon",
"yaounde"
],
"cn": [
"beijing",
"china",
"people's republic of china"
],
"co": [
"bogota",
"colombia",
"republic of colombia"
],
"cr": [
"costa rica",
"republic of costa rica",
"san jose"
],
"cs": [
"belgrade",
"serbia and montenegro"
],
"cu": [
"cuba",
"havana",
"republic of cuba"
],
"cv": [
"cabo verde",
"praia",
"republic of cabo verde"
],
"cw": [
"curacao",
"willemstad"
],
"cx": [
"christmas island",
"flying fish cove"
],
"cy": [
"cyprus",
"nicosia",
"republic of cyprus"
],
"cz": [
"czech republic",
"czechia",
"prague"
],
"de": [
"berlin",
"deutschland",
"federal republic of germany",
"germany"
],
"dj": [
"djibouti",
"republic of djibouti"
],
"dk": [
"copenhagen",
"denmark",
"kingdom of denmark"
],
"dm": [
"commonwealth of dominica",
"dominica",
"roseau"
],
"do": [
"dominican republic",
"santo domingo"
],
"dz": [
"algeria",
"algiers",
"people's democratic republic of algeria"
],
"ec": [
"ecuador",
"quito",
"republic of ecuador"
],
"ee": [
"estonia",
"republic of estonia",
"tallinn"
],
"eg": [
"arab republic of egypt",
"cairo",
"egypt"
],
"eh": [
"el-aaiun",
"western sahara"
],
"er": [
"asmara",
"eritrea",
"the state of eritrea"
],
"es": [
"kingdom of spain",
"madrid",
"spain"
],
"et": [
"addis ababa",
"ethiopia",
"federal democratic republic of ethiopia"
],
"fi": [
"finland",
"helsinki",
"republic of finland"
],
"fj": [
"fiji",
"republic of fiji",
"suva"
],
"fk": [
"falkland islands",
"falkland islands (malvinas)",
"stanley"
],
"fm": [
"federated states of micronesia",
"micronesia",
"micronesia, federated states of",
"palikir"
],
"fo": [
"faroe islands",
"torshavn"
],
"fr": [
"france",
"french republic",
"paris"
],
"ga": [
"gabon",
"gabonese republic",
"libreville"
],
"gb": [
"britain",
"england",
"great britain",
"london",
"northern ireland",
"scotland",
"u.k.",
"uk",
"united kingdom",
"united kingdom of great britain and northern ireland",
"wales"
],
"gd": [
"grenada",
"st. george's"
],
"ge": [
"georgia",
"tbilisi"
],
"gf": [
"cayenne",
"french guiana"
],
"gg": [
"guernsey",
"st peter port"
],
"gh": [
"accra",
"ghana",
"republic of ghana"
],
"gi": [
"gibraltar"
],
"gl": [
"greenland",
"nuuk"
],
"gm": [
"banjul",
"gambia",
"republic of the gambia"
],
"gn": [
"conakry",
"guinea",
"republic of guinea"
],
"gp": [
"basse-terre",
"guadeloupe"
],
"gq": [
"equatorial guinea",
"malabo",
"republic of equatorial guinea"
],
"gr": [
"athens",
"greece",
"hellenic republic"
],
"gs": [
"grytviken",
"south georgia and the south sandwich islands"
],
"gt": [
"guatemala",
"guatemala city",
"republic of guatemala"
],
"gu": [
"guam",
"hagatna"
],
"gw": [
"bissau",
"guinea-bissau",
"republic of guinea-bissau"
],
"gy": [
"georgetown",
"guyana",
"republic of guyana"
],
"hk": [
"hong kong",
"hong kong special administrative region of china"
],
"hm": [
"heard island and mcdonald islands"
],
"hn": [
"honduras",
"republic of honduras",
"tegucigalpa"
],
"hr": [
"croatia",
"republic of croatia",
"zagreb"
],
"ht": [
"haiti",
"port-au-prince",
"republic of haiti"
],
"hu": [
"budapest",
"hungary"
],
"id": [
"indonesia",
"jakarta",
"republic of indonesia"
],
"ie": [
"dublin",
"ireland"
],
"il": [
"israel",
"jerusalem",
"state of israel"
],
"im": [
"douglas",
"isle of man"
],
"in": [
"india",
"new delhi",
"republic of india"
],
"io": [
"british indian ocean territory",
"diego garcia"
],
"iq": [
"baghdad",
"iraq",
"republic of iraq"
],
"ir": [
"iran",
"iran, islamic republic of",
"islamic republic of iran",
"tehran"
],
"is": [
"iceland",
"republic of iceland",
"reykjavik"
],
"it": [
"italian republic",
"italy",
"rome"
],
"je": [
"jersey",
"saint helier"
],
"jm": [
"jamaica",
"kingston"
],
"jo": [
"amman",
"hashemite kingdom of jordan",
"jordan"
],
"jp": [
"japan",
"tokyo"
],
"ke": [
"kenya",
"nairobi",
"republic of kenya"
],
"kg": [
"bishkek",
"kyrgyz republic",
"kyrgyzstan"
],
"kh": [
"cambodia",
"kingdom of cambodia",
"phnom penh"
],
"ki": [
"kiribati",
"republic of kiribati",
"tarawa"
],
"km": [
"comoros",
"moroni",
"union of the comoros"
],
"kn": [
"basseterre",
"saint kitts and nevis"
],
"kp": [
"democratic people's republic of korea",
"korea, democratic people's republic of",
"north korea",
"pyongyang"
],
"kr": [
"korea",
"korea, republic of",
"seoul",
"south korea"
],
"kw": [
"kuwait",
"kuwait city",
"state of kuwait"
],
"ky": [
"cayman islands",
"george town"
],
"kz": [
"kazakhstan",
"nur-sultan",
"republic of kazakhstan"
],
"la": [
"lao people's democratic republic",
"laos",
"vientiane"
],
"lb": [
"beirut",
"lebanese republic",
"lebanon"
],
"lc": [
"castries",
"saint lucia"
],
"li": [
"liechtenstein",
"principality of liechtenstein",
"vaduz"
],
"lk": [
"colombo",
"democratic socialist republic of sri lanka",
"sri lanka"
],
"lr": [
"liberia",
"monrovia",
"republic of liberia"
],
"ls": [
"kingdom of lesotho",
"lesotho",
"maseru"
],
"lt": [
"lithuania",
"republic of lithuania",
"vilnius"
],
"lu": [
"grand duchy of luxembourg",
"luxembourg"
],
"lv": [
"latvia",
"republic of latvia",
"riga"
],
"ly": [
"libya",
"tripoli"
],
"ma": [
"kingdom of morocco",
"morocco",
"rabat"
],
"mc": [
"monaco",
"principality of monaco"
],
"md": [
"chisinau",
"moldova",
"moldova, republic of",
"republic of moldova"
],
"me": [
"montenegro",
"podgorica"
],
"mf": [
"marigot",
"saint martin",
"saint martin (french part)"
],
"mg": [
"antananarivo",
"madagascar",
"republic of madagascar"
],
"mh": [
"majuro",
"marshall islands",
"republic of the marshall islands"
],
"mk": [
"north macedonia",
"republic of north macedonia",
"skopje"
],
"ml": [
"bamako",
"mali",
"republic of mali"
],
"mm": [
"myanmar",
"nay pyi taw",
"republic of myanmar"
],
"mn": [
"mongolia",
"ulaanbaatar"
],
"mo": [
"macao",
"macao special administrative region of china"
],
"mp": [
"commonwealth of the northern mariana islands",
"northern mariana islands",
"saipan"
],
"mq": [
"fort-de-france",
"martinique"
],
"mr": [
"islamic republic of mauritania",
"mauritania",
"nouakchott"
],
"ms": [
"montserrat",
"plymouth"
],
"mt": [
"malta",
"republic of malta",
"valletta"
],
"mu": [
"mauritius",
"port louis",
"republic of mauritius"
],
"mv": [
"maldives",
"male",
"republic of maldives"
],
"mw": [
"lilongwe",
"malawi",
"republic of malawi"
],
"mx": [
"mexico",
"mexico city",
"united mexican states"
],
"my": [
"kuala lumpur",
"malaysia"
],
"mz": [
"maputo",
"mozambique",
"republic of mozambique"
],
"na": [
"namibia",
"republic of namibia",
"windhoek"
],
"nc": [
"new caledonia",
"noumea"
],
"ne": [
"niamey",
"niger",
"republic of the niger"
],
"nf": [
"kingston",
"norfolk island"
],
"ng": [
"abuja",
"federal republic of nigeria",
"nigeria"
],
"ni": [
"managua",
"nicaragua",
"republic of nicaragua"
],
"nl": [
"amsterdam",
"holland",
"kingdom of the netherlands",
"netherlands",
"the netherlands"
],
"no": [
"kingdom of norway",
"norway",
"oslo"
],
"np": [
"federal democratic republic of nepal",
"kathmandu",
"nepal"
],
"nr": [
"nauru",
"republic of nauru",
"yaren"
],
"nu": [
"alofi",
"niue"
],
"nz": [
"new zealand",
"wellington"
],
"om": [
"muscat",
"oman",
"sultanate of oman"
],
"pa": [
"panama",
"panama city",
"republic of panama"
],
"pe": [
"lima",
"peru",
"republic of peru"
],
"pf": [
"french polynesia",
"papeete"
],
"pg": [
"independent state of papua new guinea",
"papua new guinea",
"port moresby"
],
"ph": [
"manila",
"philippines",
"republic of the philippines"
],
"pk": [
"islamabad",
"islamic republic of pakistan",
"pakistan"
],
"pl": [
"poland",
"republic of poland",
"warsaw"
],
"pm": [
"saint pierre and miquelon",
"saint-pierre"
],
"pn": [
"adamstown",
"pitcairn"
],
"pr": [
"puerto rico",
"san juan"
],
"ps": [
"east jerusalem",
"palestine, state of",
"palestinian territory",
"the state of palestine"
],
"pt": [
"lisbon",
"portugal",
"portuguese republic"
],
"pw": [
"melekeok",
"palau",
"republic of palau"
],
"py": [
"asuncion",
"paraguay",
"republic of paraguay"
],
"qa": [
"doha",
"qatar",
"state of qatar"
],
"re": [
"reunion",
"saint-denis"
],
"ro": [
"bucharest",
"romania"
],
"rs": [
"belgrade",
"republic of serbia",
"serbia"
],
"ru": [
"moscow",
"russia",
"russian federation"
],
"rw": [
"kigali",
"rwanda",
"rwandese republic"
],
"sa": [
"kingdom of saudi arabia",
"riyadh",
"saudi arabia"
],
"sb": [
"honiara",
"solomon islands"
],
"sc": [
"republic of seychelles",
"seychelles",
"victoria"
],
"sd": [
"khartoum",
"republic of the sudan",
"sudan"
],
"se": [
"kingdom of sweden",
"stockholm",
"sweden"
],
"sg": [
"republic of singapore",
"singapore"
],
"sh": [
"jamestown",
"saint helena",
"saint helena, ascension and tristan da cunha"
],
"si": [
"ljubljana",
"republic of slovenia",
"slovenia"
],
"sj": [
"longyearbyen",
"svalbard and jan mayen"
],
"sk": [
"bratislava",
"slovak republic",
"slovakia"
],
"sl": [
"freetown",
"republic of sierra leone",
"sierra leone"
],
"sm": [
"republic of san marino",
"san marino"
],
"sn": [
"dakar",
"republic of senegal",
"senegal"
],
"so": [
"federal republic of somalia",
"mogadishu",
"somalia"
],
"sr": [
"paramaribo",
"republic of suriname",
"suriname"
],
"ss": [
"juba",
"republic of south sudan",
"south sudan"
],
"st": [
"democratic republic of sao tome and principe",
"sao tome",
"sao tome and principe"
],
"sv": [
"el salvador",
"republic of el salvador",
"san salvador"
],
"sx": [
"philipsburg",
"sint maarten",
"sint maarten (dutch part)"
],
"sy": [
"damascus",
"syria",
"syrian arab republic"
],
"sz": [
"eswatini",
"kingdom of eswatini",
"mbabane"
],
"tc": [
"cockburn town",
"turks and caicos islands"
],
"td": [
"chad",
"n'djamena",
"republic of chad"
],
"tf": [
"french southern territories",
"port-aux-francais"
],
"tg": [
"lome",
"togo",
"togolese republic"
],
"th": [
"bangkok",
"kingdom of thailand",
"thailand"
],
"tj": [
"dushanbe",
"republic of tajikistan",
"tajikistan"
],
"tk": [
"tokelau"
],
"tl": [
"democratic republic of timor-leste",
"dili",
"timor leste",
"timor-leste"
],
"tm": [
"ashgabat",
"turkmenistan"
],
"tn": [
"republic of tunisia",
"tunis",
"tunisia"
],
"to": [
"kingdom of tonga",
"nuku'alofa",
"tonga"
],
"tr": [
"ankara",
"republic of turkiye",
"turkey",
"turkiye"
],
"tt": [
"port of spain",
"republic of trinidad and tobago",
"trinidad and tobago"
],
"tv": [
"funafuti",
"tuvalu"
],
"tw": [
"taipei",
"taiwan",
"taiwan, province of china"
],
"tz": [
"dodoma",
"tanzania",
"tanzania, united republic of",
"united republic of tanzania"
],
"ua": [
"kyiv",
"ukraine"
],
"ug": [
"kampala",
"republic of uganda",
"uganda"
],
"um": [
"united states minor outlying islands"
],
"us": [
"america",
"u.s.",
"u.s.a.",
"united states",
"united states of america",
"usa",
"washington"
],
"uy": [
"eastern republic of uruguay",
"montevideo",
"uruguay"
],
"uz": [
"republic of uzbekistan",
"tashkent",
"uzbekistan"
],
"va": [
"holy see (vatican city state)",
"vatican",
"vatican city"
],
"vc": [
"kingstown",
"saint vincent and the grenadines"
],
"ve": [
"bolivarian republic of venezuela",
"caracas",
"venezuela",
"venezuela, bolivarian republic of"
],
"vg": [
"british virgin islands",
"road town",
"virgin islands, british"
],
"vi": [
"charlotte amalie",
"u.s. virgin islands",
"virgin islands of the united states",
"virgin islands, u.s."
],
"vn": [
"hanoi",
"socialist republic of viet nam",
"viet nam",
"vietnam"
],
"vu": [
"port vila",
"republic of vanuatu",
"vanuatu"
],
"wf": [
"mata utu",
"wallis and futuna"
],
"ws": [
"apia",
"independent state of samoa",
"samoa"
],
"xk": [
"kosovo",
"pristina"
],
"ye": [
"republic of yemen",
"sanaa",
"yemen"
],
"yt": [
"mamoudzou",
"mayotte"
],
"za": [
"pretoria",
"republic of south africa",
"south africa"
],
"zm": [
"lusaka",
"republic of zambia",
"zambia"
],
"zw": [
"harare",
"republic of zimbabwe",
"zimbabwe"
]
}

CITY_TOKENS = {
"ad": [],
"ae": [
"dubai",
"sharjah",
"al ain city",
"ajman city",
"dayrah",
"ras al khaimah city",
"musaffah",
"jebel ali"
],
"af": [
"herat",
"mazar-e sharif",
"kandahar",
"jalalabad"
],
"ag": [],
"ai": [],
"al": [],
"am": [],
"an": [],
"ao": [
"lubango",
"huambo",
"benguela",
"cabinda",
"malanje",
"saurimo",
"lobito",
"cuito",
"uige",
"luena",
"mossamedes",
"menongue",
"chitato",
"sumbe",
"soyo"
],
"aq": [],
"ar": [
"cordoba",
"rosario",
"mar del plata",
"san miguel de tucuman",
"salta",
"santa fe",
"corrientes",
"posadas",
"bahia blanca",
"resistencia",
"merlo",
"quilmes",
"san salvador de jujuy",
"santiago del estero",
"parana",
"neuquen",
"jose c. paz",
"formosa"
],
"as": [],
"at": [
"graz",
"linz",
"favoriten"
],
"au": [
"sydney",
"melbourne",
"brisbane",
"perth",
"adelaide",
"gold coast",
"newcastle",
"sunshine coast",
"logan city",
"wollongong",
"geelong",
"hobart"
],
"aw": [],
"ax": [],
"az": [
"sumqay\u0131t",
"ganja",
"lankaran"
],
"ba": [
"banja luka"
],
"bb": [],
"bd": [
"chattogram",
"gazipur",
"khulna",
"rangpur",
"comilla",
"rajshahi",
"pallabi",
"mirpur model thana",
"mohammadpur",
"hathazari",
"bandarban",
"shibganj",
"natore",
"kafrul",
"tungi",
"bhatara",
"savar",
"narsingdi",
"nagar naluakot",
"bagerhat"
],
"be": [
"antwerpen",
"gent",
"charleroi"
],
"bf": [
"bobo-dioulasso"
],
"bg": [
"plovdiv",
"varna"
],
"bh": [],
"bi": [
"bujumbura"
],
"bj": [
"cotonou",
"abomey-calavi",
"parakou",
"godome"
],
"bl": [],
"bm": [],
"bn": [],
"bo": [
"la paz",
"santa cruz de la sierra",
"cochabamba",
"oruro"
],
"bq": [],
"br": [
"sao paulo",
"rio de janeiro",
"belo horizonte",
"salvador",
"fortaleza",
"manaus",
"curitiba",
"recife",
"goiania",
"belem",
"porto alegre",
"guarulhos",
"maceio",
"campinas",
"sao luis",
"campo grande",
"natal",
"teresina",
"nova iguacu",
"duque de caxias"
],
"bs": [],
"bt": [],
"bv": [],
"bw": [],
"by": [
"homyel'",
"hrodna",
"vitebsk",
"mahilyow",
"brest",
"bobruysk"
],
"bz": [],
"ca": [
"toronto",
"montreal",
"calgary",
"edmonton",
"winnipeg",
"mississauga",
"vancouver",
"brampton",
"hamilton",
"surrey",
"quebec",
"halifax",
"laval",
"etobicoke",
"markham",
"vaughan",
"saskatoon",
"kitchener",
"burnaby",
"gatineau"
],
"cc": [],
"cd": [
"lubumbashi",
"mbuji-mayi",
"kananga",
"kisangani",
"bukavu",
"kolwezi",
"likasi",
"tshikapa",
"kikwit",
"masina",
"mbandaka",
"goma",
"matadi",
"uvira",
"bunia",
"boma",
"mwene",
"butembo",
"isiro",
"kindu"
],
"cf": [
"bimbo",
"begoua"
],
"cg": [
"pointe-noire"
],
"ch": [
"zurich",
"geneve"
],
"ci": [
"abidjan",
"abobo",
"bouake",
"korhogo",
"daloa",
"koumassi",
"san-pedro",
"gagnoa",
"sinfra",
"marcory"
],
"ck": [],
"cl": [
"puente alto",
"antofagasta",
"vina del mar",
"valparaiso",
"talcahuano",
"san bernardo",
"puerto montt",
"arica",
"temuco",
"concepcion",
"rancagua",
"la pintana"
],
"cm": [
"douala",
"bamenda",
"bafoussam",
"maroua",
"ngaoundere",
"kumba"
],
"cn": [
"shanghai",
"shenzhen",
"guangzhou",
"chengdu",
"tianjin",
"wuhan",
"dongguan",
"xi\u2019an",
"nanjing",
"hangzhou",
"foshan",
"chongqing",
"qingdao",
"shenyang",
"suzhou",
"harbin",
"hefei",
"dalian",
"changchun",
"xiamen"
],
"co": [
"cali",
"medellin",
"barranquilla",
"cartagena",
"cucuta",
"bucaramanga",
"ibague",
"santa marta",
"monteria",
"valledupar",
"pereira",
"manizales",
"buenaventura",
"bello",
"pasto",
"neiva",
"soledad",
"villavicencio",
"popayan",
"soacha"
],
"cr": [],
"cs": [],
"cu": [
"santiago de cuba",
"camaguey",
"holguin",
"guantanamo",
"santa clara",
"almendares",
"diez de octubre",
"arroyo naranjo",
"mantilla",
"las tunas"
],
"cv": [],
"cw": [],
"cx": [],
"cy": [],
"cz": [
"brno",
"ostrava"
],
"de": [
"hamburg",
"munich",
"koln",
"frankfurt am main",
"stuttgart",
"dusseldorf",
"essen",
"dortmund",
"dresden",
"bremen",
"nurnberg",
"hannover",
"leipzig",
"duisburg",
"wandsbek",
"bochum",
"wuppertal",
"bielefeld",
"bonn",
"hamburg-nord"
],
"dj": [],
"dk": [
"arhus"
],
"dm": [],
"do": [
"santiago de los caballeros",
"santo domingo oeste",
"santo domingo este",
"san pedro de macoris",
"la romana"
],
"dz": [
"oran",
"constantine",
"annaba",
"blida",
"batna city",
"bab ezzouar",
"djelfa",
"setif",
"sidi bel abbes",
"biskra"
],
"ec": [
"guayaquil",
"cuenca",
"santo domingo de los colorados",
"ambato",
"portoviejo",
"eloy alfaro",
"machala",
"loja",
"manta",
"riobamba",
"ibarra",
"esmeraldas",
"quevedo",
"latacunga"
],
"ee": [],
"eg": [
"alexandria",
"giza",
"shubra al khaymah",
"port said",
"suez",
"madinat an nasr",
"al mansurah",
"al mahallah al kubra",
"tanta",
"assiut",
"al fayyum",
"al khusus",
"zagazig",
"ismailia",
"luxor",
"aswan",
"6th of october city",
"hada\u2019iq al qubbah",
"damanhur",
"new cairo"
],
"eh": [],
"er": [],
"es": [
"barcelona",
"sevilla",
"zaragoza",
"malaga",
"murcia",
"palma",
"las palmas de gran canaria",
"alicante",
"bilbao",
"valladolid",
"vigo",
"gijon",
"eixample",
"l'hospitalet de llobregat",
"latina",
"carabanchel",
"a coruna",
"gasteiz / vitoria",
"puente de vallecas",
"fuencarral"
],
"et": [
"jijiga",
"gonder",
"mek'ele",
"nazret",
"awasa",
"bahir dar",
"dire dawa",
"dessie",
"jimma",
"shashamane",
"bishoftu",
"sodo",
"arba minch"
],
"fi": [
"espoo",
"tampere",
"oulu"
],
"fj": [],
"fk": [],
"fm": [],
"fo": [],
"fr": [
"marseille",
"lyon",
"toulouse",
"nice",
"nantes",
"marne la vallee",
"strasbourg",
"bordeaux",
"montpellier",
"rouen",
"lille",
"rennes"
],
"ga": [],
"gb": [
"birmingham",
"glasgow",
"manchester",
"sheffield",
"leeds",
"edinburgh",
"liverpool",
"bristol",
"cardiff",
"leicester",
"bradford",
"belfast",
"coventry",
"brent",
"birkenhead",
"nottingham",
"islington",
"reading",
"kingston upon hull",
"preston"
],
"gd": [],
"ge": [],
"gf": [],
"gg": [],
"gh": [
"kumasi",
"tamale",
"takoradi",
"sekondi",
"cape coast",
"atsiaman"
],
"gi": [],
"gl": [],
"gm": [
"serekunda"
],
"gn": [
"camayenne",
"nzerekore",
"kankan"
],
"gp": [],
"gq": [],
"gr": [
"thessaloniki"
],
"gs": [],
"gt": [
"villa nueva",
"mixco",
"coban"
],
"gu": [],
"gw": [],
"gy": [],
"hk": [
"new territories",
"kowloon",
"hong kong island",
"victoria",
"tuen mun",
"sha tin",
"sham shui po",
"wong tai sin",
"kowloon city",
"tseung kwan o",
"kwai chung",
"tsuen wan",
"tin shui wai",
"tai po",
"fanling",
"ma on shan",
"yuen long san hui",
"yuen long"
],
"hm": [],
"hn": [
"san pedro sula",
"la ceiba"
],
"hr": [],
"ht": [
"carrefour",
"delmas",
"port-de-paix",
"petionville",
"croix-des-bouquets"
],
"hu": [
"debrecen"
],
"id": [
"surabaya",
"bekasi",
"bandung",
"medan",
"depok",
"tangerang",
"palembang",
"semarang",
"makassar",
"south tangerang",
"jepara",
"bandar lampung",
"batam",
"bogor",
"pekanbaru",
"padang",
"malang",
"samarinda",
"tasikmalaya",
"denpasar"
],
"ie": [
"south dublin"
],
"il": [
"tel aviv",
"west jerusalem",
"haifa",
"rishon letsiyyon",
"petah tiqva",
"netanya",
"ashdod",
"bnei brak"
],
"im": [],
"in": [
"mumbai",
"delhi",
"bengaluru",
"hyderabad",
"ahmedabad",
"chennai",
"kolkata",
"surat",
"pune",
"jaipur",
"kanpur",
"navi mumbai",
"lucknow",
"nagpur",
"coimbatore",
"indore",
"thane",
"vadodara",
"bhopal",
"rasapudipalem"
],
"io": [],
"iq": [
"al mawsil al jadidah",
"al basrah al qadimah",
"mosul",
"erbil",
"basrah",
"karbala",
"kirkuk",
"abu ghurayb",
"as sulaymaniyah",
"nasiriyah",
"najaf",
"al hillah",
"al mahmudiyah",
"dihok",
"al \u2018amarah",
"ad diwaniyah",
"al kut",
"al qurnah",
"al madinah",
"kelar"
],
"ir": [
"mashhad",
"isfahan",
"karaj",
"tabriz",
"shiraz",
"ahvaz",
"pasragad branch",
"kermanshah",
"rasht",
"kerman",
"orumiyeh",
"zahedan",
"hamadan",
"azadshahr",
"arak",
"yazd",
"eslamshahr",
"ardabil",
"abadan",
"zanjan"
],
"is": [],
"it": [
"milan",
"naples",
"turin",
"palermo",
"genoa",
"bologna",
"florence",
"bari",
"catania",
"verona",
"messina",
"trieste",
"padova",
"brescia"
],
"je": [],
"jm": [
"new kingston"
],
"jo": [
"zarqa",
"irbid",
"russeifa",
"hayy khilda"
],
"jp": [
"yokohama",
"osaka",
"nagoya",
"sapporo",
"fukuoka",
"kawasaki",
"kobe",
"kyoto",
"saitama",
"hiroshima",
"sendai",
"chiba",
"kitakyushu",
"setagaya",
"sakai",
"niigata",
"hamamatsu",
"kumamoto",
"aihara",
"okayama"
],
"ke": [
"kakamega",
"mombasa",
"nakuru",
"ruiru",
"eldoret",
"kisumu",
"kikuyu",
"thika"
],
"kg": [],
"kh": [
"takeo"
],
"ki": [],
"km": [],
"kn": [],
"kp": [
"hamhung",
"namp\u2019o",
"sunch\u2019on",
"hungnam",
"kaesong",
"wonsan",
"chongjin",
"man\u2019gyongdae-ri",
"kaech\u2019on",
"sariwon-si",
"sinuiju",
"tokch\u2019on",
"haeju",
"kanggye",
"changam-ch\u2019on"
],
"kr": [
"busan",
"incheon",
"daegu",
"daejeon",
"gwangju",
"suwon",
"ulsan",
"goyang-si",
"changwon",
"seongnam-si",
"cheongju-si",
"bucheon-si",
"cheonan",
"hwaseong-si",
"jeonju",
"ansan-si",
"anyang-si",
"kimhae",
"pohang",
"jeju city"
],
"kw": [
"al ahmadi"
],
"ky": [],
"kz": [
"almaty",
"shymkent",
"aktobe",
"karagandy",
"taraz",
"kyzylorda",
"astana",
"oral",
"pavlodar",
"ust-kamenogorsk",
"semey",
"atyrau",
"turkestan",
"kostanay",
"petropavl"
],
"la": [],
"lb": [
"ra\u2019s bayrut"
],
"lc": [],
"li": [],
"lk": [
"dehiwala-mount lavinia"
],
"lr": [],
"ls": [],
"lt": [
"kaunas"
],
"lu": [],
"lv": [],
"ly": [
"benghazi",
"misratah",
"zliten",
"al khums",
"az zawiyah"
],
"ma": [
"casablanca",
"tangier",
"marrakesh",
"sale",
"agadir",
"meknes",
"oujda",
"kenitra",
"tetouan",
"al hoceima",
"temara",
"safi",
"mohammedia",
"khouribga",
"el jadida",
"beni mellal",
"sale al jadida"
],
"mc": [],
"md": [],
"me": [],
"mf": [],
"mg": [
"toamasina",
"antsirabe",
"mahajanga",
"fianarantsoa"
],
"mh": [],
"mk": [],
"ml": [
"sikasso",
"koutiala",
"segou"
],
"mm": [
"yangon",
"mandalay",
"mawlamyine",
"insein",
"kyain seikgyi township",
"bago",
"amarapura",
"pathein"
],
"mn": [
"ulan bator"
],
"mo": [
"macau"
],
"mp": [],
"mq": [],
"mr": [],
"ms": [],
"mt": [],
"mu": [],
"mv": [],
"mw": [
"blantyre",
"mzuzu"
],
"mx": [
"tijuana",
"iztapalapa",
"puebla",
"ecatepec de morelos",
"santiago de queretaro",
"leon de los aldama",
"ciudad juarez",
"zapopan",
"guadalajara",
"merida",
"gustavo adolfo madero",
"monterrey",
"ciudad nezahualcoyotl",
"mexicali",
"chihuahua",
"naucalpan de juarez",
"hermosillo",
"culiacan",
"morelia",
"torreon"
],
"my": [
"klang",
"johor bahru",
"kampung baru subang",
"petaling jaya",
"ipoh",
"shah alam",
"subang jaya",
"bukit rahman putra",
"pelentong",
"malacca",
"iskandar puteri",
"kota bharu",
"kuantan",
"kota kuala muda",
"selayang baru utara",
"mukim pulai",
"kota kinabalu",
"kampung larkin lama",
"kota damansara",
"sandakan"
],
"mz": [
"matola",
"nampula",
"beira",
"chimoio",
"tete",
"quelimane",
"lichinga",
"nacala",
"pemba"
],
"na": [],
"nc": [],
"ne": [
"maradi",
"zinder"
],
"nf": [],
"ng": [
"lagos",
"kano",
"ibadan",
"port harcourt",
"kaduna",
"benin city",
"onitsha",
"maiduguri",
"ilorin",
"sokoto",
"zaria",
"enugu",
"warri",
"abeokuta",
"akure",
"bauchi",
"katsina",
"osogbo",
"ile-ife",
"gombe"
],
"ni": [],
"nl": [
"rotterdam",
"the hague",
"utrecht",
"groningen",
"eindhoven"
],
"no": [
"bergen",
"trondheim"
],
"np": [
"pokhara",
"bharatpur",
"patan",
"birganj",
"biratnagar",
"dhangadhi"
],
"nr": [],
"nu": [],
"nz": [
"auckland",
"christchurch",
"manukau city",
"north shore"
],
"om": [
"seeb",
"bawshar"
],
"pa": [
"san miguelito"
],
"pe": [
"callao",
"arequipa",
"trujillo",
"chiclayo",
"piura",
"huancayo",
"cusco",
"iquitos",
"pucallpa",
"chimbote",
"tacna",
"santiago de surco",
"juliaca",
"cajamarca"
],
"pf": [],
"pg": [],
"ph": [
"quezon city",
"davao",
"caloocan city",
"budta",
"malingao",
"zamboanga",
"cebu city",
"antipolo",
"cagayan de oro",
"valenzuela",
"general santos",
"paranaque city",
"taguig",
"pasig city",
"las pinas",
"calamba",
"makati city",
"iloilo",
"bacolod city",
"mansilingan"
],
"pk": [
"lahore",
"karachi",
"peshawar",
"faisalabad",
"rawalpindi",
"gujranwala",
"multan",
"quetta",
"bannu",
"sargodha",
"sialkot",
"bahawalpur",
"dera ismail khan",
"muzaffarabad",
"battagram",
"kotli",
"shekhupura",
"gujrat",
"sukkur",
"sahiwal"
],
"pl": [
"\u0142odz",
"krakow",
"wroc\u0142aw",
"poznan",
"gdansk",
"szczecin",
"bydgoszcz",
"lublin",
"katowice",
"bia\u0142ystok",
"gdynia",
"czestochowa",
"sosnowiec",
"radom",
"mokotow",
"kielce"
],
"pm": [],
"pn": [],
"pr": [
"bayamon"
],
"ps": [
"gaza"
],
"pt": [
"porto"
],
"pw": [],
"py": [
"ciudad del este",
"san lorenzo"
],
"qa": [
"ar rayyan"
],
"re": [],
"ro": [
"sector 3",
"iasi",
"sector 6",
"constanta",
"sector 2",
"sector 4",
"cluj-napoca",
"sector 5",
"brasov",
"timisoara",
"craiova",
"sector 1",
"galati",
"targu mures"
],
"rs": [
"novi sad"
],
"ru": [
"saint petersburg",
"novosibirsk",
"yekaterinburg",
"nizhniy novgorod",
"kazan",
"chelyabinsk",
"omsk",
"samara",
"rostov-na-donu",
"krasnoyarsk",
"voronezh",
"volgograd",
"perm",
"krasnodar",
"saratov",
"tyumen",
"tolyatti",
"izhevsk",
"barnaul",
"ulyanovsk"
],
"rw": [],
"sa": [
"jeddah",
"makkah",
"madinah",
"dammam",
"sultanah",
"buraydah",
"ta\u2019if",
"tabuk",
"ha'il",
"najran",
"al kharj",
"khamis mushait",
"al hufuf",
"al mubarraz",
"hafar al-batin",
"thuqbah",
"al jubayl",
"abha",
"yanbu"
],
"sb": [],
"sc": [],
"sd": [
"omdurman",
"khartoum north",
"nyala",
"port sudan",
"kassala",
"el obeid",
"al qadarif",
"kosti",
"wad medani",
"el daein",
"el fasher",
"singa"
],
"se": [
"goteborg",
"malmo"
],
"sg": [
"ulu bedok",
"bedok new town",
"tampines estate",
"jurong town",
"tampines new town",
"jurong west",
"woodlands",
"sengkang new town",
"hougang new town",
"yishun new town"
],
"sh": [],
"si": [],
"sj": [],
"sk": [
"kosice"
],
"sl": [],
"sm": [],
"sn": [
"touba",
"pikine",
"guediawaye",
"thies",
"kaolack",
"rufisque",
"mbour",
"saint-louis",
"thies nones",
"rufisque est",
"ziguinchor"
],
"so": [
"borama",
"hargeysa",
"berbera",
"kismayo",
"marka"
],
"sr": [],
"ss": [
"winejok"
],
"st": [],
"sv": [
"soyapango",
"san miguel"
],
"sx": [],
"sy": [
"aleppo",
"homs",
"latakia",
"ar raqqah",
"hamah",
"tartus",
"al hasakah",
"deir ez-zor"
],
"sz": [],
"tc": [],
"td": [],
"tf": [],
"tg": [],
"th": [
"samut prakan",
"mueang nonthaburi",
"chon buri"
],
"tj": [
"isfara",
"istaravshan",
"kulob",
"konibodom"
],
"tk": [],
"tl": [],
"tm": [
"turkmenabat"
],
"tn": [
"sfax",
"sousse"
],
"to": [],
"tr": [
"istanbul",
"bursa",
"izmir",
"gaziantep",
"adana",
"diyarbak\u0131r",
"kayseri",
"konya",
"antalya",
"malatya",
"cankaya",
"eskisehir",
"erzurum",
"bagc\u0131lar",
"bahcelievler",
"umraniye",
"mersin",
"uskudar",
"esenler",
"karabaglar"
],
"tt": [],
"tv": [],
"tw": [
"new taipei city",
"taichung",
"kaohsiung",
"tainan",
"banqiao",
"taoyuan",
"hsinchu",
"taoyuan city",
"keelung",
"fengshan",
"neihu",
"chiayi city",
"yongkang",
"chang-hua",
"changhua",
"zhubei",
"bade",
"xizhi"
],
"tz": [
"dar es salaam",
"mwanza",
"zanzibar",
"arusha",
"mbeya",
"morogoro",
"kahama",
"tanga",
"geita",
"tabora",
"sumbawanga",
"songea",
"kibaha",
"bariadi",
"kasulu",
"singida",
"kigoma",
"moshi",
"tunduma",
"ifakara"
],
"ua": [
"kharkiv",
"odesa",
"dnipro",
"donetsk",
"lviv",
"zaporizhzhya",
"kryvyy rih",
"sevastopol",
"mykolayiv",
"saltivka",
"luhansk",
"vinnytsya",
"stara darnytsya",
"makiivka",
"simferopol",
"chernihiv",
"kherson",
"poltava",
"khmelnytskyi",
"cherkasy"
],
"ug": [
"nansana",
"kira",
"bunamwaya",
"kyengera",
"mbarara",
"kasangati"
],
"um": [],
"us": [
"new york city",
"los angeles",
"brooklyn",
"chicago",
"queens",
"houston",
"phoenix",
"philadelphia",
"san antonio",
"manhattan",
"san diego",
"the bronx",
"dallas",
"jacksonville",
"fort worth",
"san jose",
"austin",
"columbus",
"charlotte",
"indianapolis"
],
"uy": [],
"uz": [
"andijon",
"namangan",
"samarkand",
"yunusobod",
"nukus",
"fergana",
"bukhara",
"qarshi",
"chilanzar",
"qo\u2018qon",
"marg\u2018ilon"
],
"va": [],
"vc": [],
"ve": [
"maracaibo",
"valencia",
"barquisimeto",
"ciudad guayana",
"maturin",
"maracay",
"ciudad bolivar",
"cumana",
"barinas",
"puerto la cruz",
"petare",
"cabimas",
"turmero",
"san cristobal",
"alto barinas",
"santa teresa del tuy",
"los teques",
"guarenas",
"coro",
"valera"
],
"vg": [],
"vi": [],
"vn": [
"ho chi minh city",
"haiphong",
"can tho",
"da nang",
"bien hoa",
"thanh hoa",
"vinh",
"thuan an",
"nha trang",
"cho lon",
"thu \u0111uc",
"qui nhon",
"vung tau",
"di an",
"rach gia",
"bac giang",
"nam \u0111inh",
"buon ma thuot",
"thai nguyen",
"viet tri"
],
"vu": [],
"wf": [],
"ws": [],
"xk": [],
"ye": [
"aden",
"taiz",
"al hudaydah",
"mukalla"
],
"yt": [],
"za": [
"johannesburg",
"cape town",
"durban",
"soweto",
"port elizabeth",
"soshanguve",
"pietermaritzburg",
"evaton",
"benoni",
"bloemfontein",
"thembisa",
"east london",
"vereeniging",
"boksburg",
"welkom",
"krugersdorp",
"rustenburg",
"emalahleni",
"diepsloot",
"randburg"
],
"zm": [
"kitwe",
"ndola",
"chipata",
"solwezi",
"kabwe",
"chingola"
],
"zw": [
"bulawayo",
"chitungwiza",
"mutare",
"epworth"
]
}

COUNTRY_TOKENS = {
"ad": [
"andorra",
"andorra la vella",
"principality of andorra"
],
"ae": [
"abu dhabi",
"ajman city",
"al ain city",
"dayrah",
"dubai",
"jebel ali",
"musaffah",
"ras al khaimah city",
"sharjah",
"u.a.e.",
"uae",
"united arab emirates"
],
"af": [
"afghanistan",
"herat",
"islamic republic of afghanistan",
"jalalabad",
"kabul",
"kandahar",
"mazar-e sharif"
],
"ag": [
"antigua and barbuda",
"st. john's"
],
"ai": [
"anguilla",
"the valley"
],
"al": [
"albania",
"republic of albania",
"tirana"
],
"am": [
"armenia",
"republic of armenia",
"yerevan"
],
"an": [
"netherlands antilles",
"willemstad"
],
"ao": [
"angola",
"benguela",
"cabinda",
"chitato",
"cuito",
"huambo",
"lobito",
"luanda",
"lubango",
"luena",
"malanje",
"menongue",
"mossamedes",
"republic of angola",
"saurimo",
"soyo",
"sumbe",
"uige"
],
"aq": [
"antarctica"
],
"ar": [
"argentina",
"argentine republic",
"bahia blanca",
"buenos aires",
"cordoba",
"corrientes",
"formosa",
"jose c. paz",
"mar del plata",
"merlo",
"neuquen",
"parana",
"posadas",
"quilmes",
"resistencia",
"rosario",
"salta",
"san miguel de tucuman",
"san salvador de jujuy",
"santa fe",
"santiago del estero"
],
"as": [
"american samoa",
"pago pago"
],
"at": [
"austria",
"favoriten",
"graz",
"linz",
"republic of austria",
"vienna"
],
"au": [
"adelaide",
"australia",
"brisbane",
"canberra",
"geelong",
"gold coast",
"hobart",
"logan city",
"melbourne",
"newcastle",
"perth",
"sunshine coast",
"sydney",
"wollongong"
],
"aw": [
"aruba",
"oranjestad"
],
"ax": [
"aland islands",
"mariehamn"
],
"az": [
"azerbaijan",
"baku",
"ganja",
"lankaran",
"republic of azerbaijan",
"sumqay\u0131t"
],
"ba": [
"banja luka",
"bosnia and herzegovina",
"republic of bosnia and herzegovina",
"sarajevo"
],
"bb": [
"barbados",
"bridgetown"
],
"bd": [
"bagerhat",
"bandarban",
"bangladesh",
"bhatara",
"chattogram",
"comilla",
"dhaka",
"gazipur",
"hathazari",
"kafrul",
"khulna",
"mirpur model thana",
"mohammadpur",
"nagar naluakot",
"narsingdi",
"natore",
"pallabi",
"people's republic of bangladesh",
"rajshahi",
"rangpur",
"savar",
"shibganj",
"tungi"
],
"be": [
"antwerpen",
"belgium",
"brussels",
"charleroi",
"gent",
"kingdom of belgium"
],
"bf": [
"bobo-dioulasso",
"burkina faso",
"ouagadougou"
],
"bg": [
"bulgaria",
"plovdiv",
"republic of bulgaria",
"sofia",
"varna"
],
"bh": [
"bahrain",
"kingdom of bahrain",
"manama"
],
"bi": [
"bujumbura",
"burundi",
"gitega",
"republic of burundi"
],
"bj": [
"abomey-calavi",
"benin",
"cotonou",
"godome",
"parakou",
"porto-novo",
"republic of benin"
],
"bl": [
"gustavia",
"saint barthelemy"
],
"bm": [
"bermuda",
"hamilton"
],
"bn": [
"bandar seri begawan",
"brunei",
"brunei darussalam"
],
"bo": [
"bolivia",
"bolivia, plurinational state of",
"cochabamba",
"la paz",
"oruro",
"plurinational state of bolivia",
"santa cruz de la sierra",
"sucre"
],
"bq": [
"bonaire, saint eustatius and saba",
"bonaire, sint eustatius and saba"
],
"br": [
"belem",
"belo horizonte",
"brasilia",
"brazil",
"campinas",
"campo grande",
"curitiba",
"duque de caxias",
"federative republic of brazil",
"fortaleza",
"goiania",
"guarulhos",
"maceio",
"manaus",
"natal",
"nova iguacu",
"porto alegre",
"recife",
"rio de janeiro",
"salvador",
"sao luis",
"sao paulo",
"teresina"
],
"bs": [
"bahamas",
"commonwealth of the bahamas",
"nassau"
],
"bt": [
"bhutan",
"kingdom of bhutan",
"thimphu"
],
"bv": [
"bouvet island"
],
"bw": [
"botswana",
"gaborone",
"republic of botswana"
],
"by": [
"belarus",
"bobruysk",
"brest",
"homyel'",
"hrodna",
"mahilyow",
"minsk",
"republic of belarus",
"vitebsk"
],
"bz": [
"belize",
"belmopan"
],
"ca": [
"brampton",
"burnaby",
"calgary",
"canada",
"edmonton",
"etobicoke",
"gatineau",
"halifax",
"hamilton",
"kitchener",
"laval",
"markham",
"mississauga",
"montreal",
"ottawa",
"quebec",
"saskatoon",
"surrey",
"toronto",
"vancouver",
"vaughan",
"winnipeg"
],
"cc": [
"cocos (keeling) islands",
"cocos islands",
"west island"
],
"cd": [
"boma",
"bukavu",
"bunia",
"butembo",
"congo, the democratic republic of the",
"democratic republic of the congo",
"goma",
"isiro",
"kananga",
"kikwit",
"kindu",
"kinshasa",
"kisangani",
"kolwezi",
"likasi",
"lubumbashi",
"masina",
"matadi",
"mbandaka",
"mbuji-mayi",
"mwene",
"tshikapa",
"uvira"
],
"cf": [
"bangui",
"begoua",
"bimbo",
"central african republic"
],
"cg": [
"brazzaville",
"congo",
"pointe-noire",
"republic of the congo"
],
"ch": [
"bern",
"geneve",
"swiss confederation",
"switzerland",
"zurich"
],
"ci": [
"abidjan",
"abobo",
"bouake",
"cote d'ivoire",
"daloa",
"gagnoa",
"ivory coast",
"korhogo",
"koumassi",
"marcory",
"republic of cote d'ivoire",
"san-pedro",
"sinfra",
"yamoussoukro"
],
"ck": [
"avarua",
"cook islands"
],
"cl": [
"antofagasta",
"arica",
"chile",
"concepcion",
"la pintana",
"puente alto",
"puerto montt",
"rancagua",
"republic of chile",
"san bernardo",
"santiago",
"talcahuano",
"temuco",
"valparaiso",
"vina del mar"
],
"cm": [
"bafoussam",
"bamenda",
"cameroon",
"douala",
"kumba",
"maroua",
"ngaoundere",
"republic of cameroon",
"yaounde"
],
"cn": [
"beijing",
"changchun",
"chengdu",
"china",
"chongqing",
"dalian",
"dongguan",
"foshan",
"guangzhou",
"hangzhou",
"harbin",
"hefei",
"nanjing",
"people's republic of china",
"qingdao",
"shanghai",
"shenyang",
"shenzhen",
"suzhou",
"tianjin",
"wuhan",
"xiamen",
"xi\u2019an"
],
"co": [
"barranquilla",
"bello",
"bogota",
"bucaramanga",
"buenaventura",
"cali",
"cartagena",
"colombia",
"cucuta",
"ibague",
"manizales",
"medellin",
"monteria",
"neiva",
"pasto",
"pereira",
"popayan",
"republic of colombia",
"santa marta",
"soacha",
"soledad",
"valledupar",
"villavicencio"
],
"cr": [
"costa rica",
"republic of costa rica",
"san jose"
],
"cs": [
"belgrade",
"serbia and montenegro"
],
"cu": [
"almendares",
"arroyo naranjo",
"camaguey",
"cuba",
"diez de octubre",
"guantanamo",
"havana",
"holguin",
"las tunas",
"mantilla",
"republic of cuba",
"santa clara",
"santiago de cuba"
],
"cv": [
"cabo verde",
"praia",
"republic of cabo verde"
],
"cw": [
"curacao",
"willemstad"
],
"cx": [
"christmas island",
"flying fish cove"
],
"cy": [
"cyprus",
"nicosia",
"republic of cyprus"
],
"cz": [
"brno",
"czech republic",
"czechia",
"ostrava",
"prague"
],
"de": [
"berlin",
"bielefeld",
"bochum",
"bonn",
"bremen",
"deutschland",
"dortmund",
"dresden",
"duisburg",
"dusseldorf",
"essen",
"federal republic of germany",
"frankfurt am main",
"germany",
"hamburg",
"hamburg-nord",
"hannover",
"koln",
"leipzig",
"munich",
"nurnberg",
"stuttgart",
"wandsbek",
"wuppertal"
],
"dj": [
"djibouti",
"republic of djibouti"
],
"dk": [
"arhus",
"copenhagen",
"denmark",
"kingdom of denmark"
],
"dm": [
"commonwealth of dominica",
"dominica",
"roseau"
],
"do": [
"dominican republic",
"la romana",
"san pedro de macoris",
"santiago de los caballeros",
"santo domingo",
"santo domingo este",
"santo domingo oeste"
],
"dz": [
"algeria",
"algiers",
"annaba",
"bab ezzouar",
"batna city",
"biskra",
"blida",
"constantine",
"djelfa",
"oran",
"people's democratic republic of algeria",
"setif",
"sidi bel abbes"
],
"ec": [
"ambato",
"cuenca",
"ecuador",
"eloy alfaro",
"esmeraldas",
"guayaquil",
"ibarra",
"latacunga",
"loja",
"machala",
"manta",
"portoviejo",
"quevedo",
"quito",
"republic of ecuador",
"riobamba",
"santo domingo de los colorados"
],
"ee": [
"estonia",
"republic of estonia",
"tallinn"
],
"eg": [
"6th of october city",
"al fayyum",
"al khusus",
"al mahallah al kubra",
"al mansurah",
"alexandria",
"arab republic of egypt",
"assiut",
"aswan",
"cairo",
"damanhur",
"egypt",
"giza",
"hada\u2019iq al qubbah",
"ismailia",
"luxor",
"madinat an nasr",
"new cairo",
"port said",
"shubra al khaymah",
"suez",
"tanta",
"zagazig"
],
"eh": [
"el-aaiun",
"western sahara"
],
"er": [
"asmara",
"eritrea",
"the state of eritrea"
],
"es": [
"a coruna",
"alicante",
"barcelona",
"bilbao",
"carabanchel",
"eixample",
"fuencarral",
"gasteiz / vitoria",
"gijon",
"kingdom of spain",
"l'hospitalet de llobregat",
"las palmas de gran canaria",
"latina",
"madrid",
"malaga",
"murcia",
"palma",
"puente de vallecas",
"sevilla",
"spain",
"valladolid",
"vigo",
"zaragoza"
],
"et": [
"addis ababa",
"arba minch",
"awasa",
"bahir dar",
"bishoftu",
"dessie",
"dire dawa",
"ethiopia",
"federal democratic republic of ethiopia",
"gonder",
"jijiga",
"jimma",
"mek'ele",
"nazret",
"shashamane",
"sodo"
],
"fi": [
"espoo",
"finland",
"helsinki",
"oulu",
"republic of finland",
"tampere"
],
"fj": [
"fiji",
"republic of fiji",
"suva"
],
"fk": [
"falkland islands",
"falkland islands (malvinas)",
"stanley"
],
"fm": [
"federated states of micronesia",
"micronesia",
"micronesia, federated states of",
"palikir"
],
"fo": [
"faroe islands",
"torshavn"
],
"fr": [
"bordeaux",
"france",
"french republic",
"lille",
"lyon",
"marne la vallee",
"marseille",
"montpellier",
"nantes",
"nice",
"paris",
"rennes",
"rouen",
"strasbourg",
"toulouse"
],
"ga": [
"gabon",
"gabonese republic",
"libreville"
],
"gb": [
"belfast",
"birkenhead",
"birmingham",
"bradford",
"brent",
"bristol",
"britain",
"cardiff",
"coventry",
"edinburgh",
"england",
"glasgow",
"great britain",
"islington",
"kingston upon hull",
"leeds",
"leicester",
"liverpool",
"london",
"manchester",
"northern ireland",
"nottingham",
"preston",
"reading",
"scotland",
"sheffield",
"u.k.",
"uk",
"united kingdom",
"united kingdom of great britain and northern ireland",
"wales"
],
"gd": [
"grenada",
"st. george's"
],
"ge": [
"georgia",
"tbilisi"
],
"gf": [
"cayenne",
"french guiana"
],
"gg": [
"guernsey",
"st peter port"
],
"gh": [
"accra",
"atsiaman",
"cape coast",
"ghana",
"kumasi",
"republic of ghana",
"sekondi",
"takoradi",
"tamale"
],
"gi": [
"gibraltar"
],
"gl": [
"greenland",
"nuuk"
],
"gm": [
"banjul",
"gambia",
"republic of the gambia",
"serekunda"
],
"gn": [
"camayenne",
"conakry",
"guinea",
"kankan",
"nzerekore",
"republic of guinea"
],
"gp": [
"basse-terre",
"guadeloupe"
],
"gq": [
"equatorial guinea",
"malabo",
"republic of equatorial guinea"
],
"gr": [
"athens",
"greece",
"hellenic republic",
"thessaloniki"
],
"gs": [
"grytviken",
"south georgia and the south sandwich islands"
],
"gt": [
"coban",
"guatemala",
"guatemala city",
"mixco",
"republic of guatemala",
"villa nueva"
],
"gu": [
"guam",
"hagatna"
],
"gw": [
"bissau",
"guinea-bissau",
"republic of guinea-bissau"
],
"gy": [
"georgetown",
"guyana",
"republic of guyana"
],
"hk": [
"fanling",
"hong kong",
"hong kong island",
"hong kong special administrative region of china",
"kowloon",
"kowloon city",
"kwai chung",
"ma on shan",
"new territories",
"sha tin",
"sham shui po",
"tai po",
"tin shui wai",
"tseung kwan o",
"tsuen wan",
"tuen mun",
"victoria",
"wong tai sin",
"yuen long",
"yuen long san hui"
],
"hm": [
"heard island and mcdonald islands"
],
"hn": [
"honduras",
"la ceiba",
"republic of honduras",
"san pedro sula",
"tegucigalpa"
],
"hr": [
"croatia",
"republic of croatia",
"zagreb"
],
"ht": [
"carrefour",
"croix-des-bouquets",
"delmas",
"haiti",
"petionville",
"port-au-prince",
"port-de-paix",
"republic of haiti"
],
"hu": [
"budapest",
"debrecen",
"hungary"
],
"id": [
"bandar lampung",
"bandung",
"batam",
"bekasi",
"bogor",
"denpasar",
"depok",
"indonesia",
"jakarta",
"jepara",
"makassar",
"malang",
"medan",
"padang",
"palembang",
"pekanbaru",
"republic of indonesia",
"samarinda",
"semarang",
"south tangerang",
"surabaya",
"tangerang",
"tasikmalaya"
],
"ie": [
"dublin",
"ireland",
"south dublin"
],
"il": [
"ashdod",
"bnei brak",
"haifa",
"israel",
"jerusalem",
"netanya",
"petah tiqva",
"rishon letsiyyon",
"state of israel",
"tel aviv",
"west jerusalem"
],
"im": [
"douglas",
"isle of man"
],
"in": [
"ahmedabad",
"bengaluru",
"bhopal",
"chennai",
"coimbatore",
"delhi",
"hyderabad",
"india",
"indore",
"jaipur",
"kanpur",
"kolkata",
"lucknow",
"mumbai",
"nagpur",
"navi mumbai",
"new delhi",
"pune",
"rasapudipalem",
"republic of india",
"surat",
"thane",
"vadodara"
],
"io": [
"british indian ocean territory",
"diego garcia"
],
"iq": [
"abu ghurayb",
"ad diwaniyah",
"al basrah al qadimah",
"al hillah",
"al kut",
"al madinah",
"al mahmudiyah",
"al mawsil al jadidah",
"al qurnah",
"al \u2018amarah",
"as sulaymaniyah",
"baghdad",
"basrah",
"dihok",
"erbil",
"iraq",
"karbala",
"kelar",
"kirkuk",
"mosul",
"najaf",
"nasiriyah",
"republic of iraq"
],
"ir": [
"abadan",
"ahvaz",
"arak",
"ardabil",
"azadshahr",
"eslamshahr",
"hamadan",
"iran",
"iran, islamic republic of",
"isfahan",
"islamic republic of iran",
"karaj",
"kerman",
"kermanshah",
"mashhad",
"orumiyeh",
"pasragad branch",
"rasht",
"shiraz",
"tabriz",
"tehran",
"yazd",
"zahedan",
"zanjan"
],
"is": [
"iceland",
"republic of iceland",
"reykjavik"
],
"it": [
"bari",
"bologna",
"brescia",
"catania",
"florence",
"genoa",
"italian republic",
"italy",
"messina",
"milan",
"naples",
"padova",
"palermo",
"rome",
"trieste",
"turin",
"verona"
],
"je": [
"jersey",
"saint helier"
],
"jm": [
"jamaica",
"kingston",
"new kingston"
],
"jo": [
"amman",
"hashemite kingdom of jordan",
"hayy khilda",
"irbid",
"jordan",
"russeifa",
"zarqa"
],
"jp": [
"aihara",
"chiba",
"fukuoka",
"hamamatsu",
"hiroshima",
"japan",
"kawasaki",
"kitakyushu",
"kobe",
"kumamoto",
"kyoto",
"nagoya",
"niigata",
"okayama",
"osaka",
"saitama",
"sakai",
"sapporo",
"sendai",
"setagaya",
"tokyo",
"yokohama"
],
"ke": [
"eldoret",
"kakamega",
"kenya",
"kikuyu",
"kisumu",
"mombasa",
"nairobi",
"nakuru",
"republic of kenya",
"ruiru",
"thika"
],
"kg": [
"bishkek",
"kyrgyz republic",
"kyrgyzstan"
],
"kh": [
"cambodia",
"kingdom of cambodia",
"phnom penh",
"takeo"
],
"ki": [
"kiribati",
"republic of kiribati",
"tarawa"
],
"km": [
"comoros",
"moroni",
"union of the comoros"
],
"kn": [
"basseterre",
"saint kitts and nevis"
],
"kp": [
"changam-ch\u2019on",
"chongjin",
"democratic people's republic of korea",
"haeju",
"hamhung",
"hungnam",
"kaech\u2019on",
"kaesong",
"kanggye",
"korea, democratic people's republic of",
"man\u2019gyongdae-ri",
"namp\u2019o",
"north korea",
"pyongyang",
"sariwon-si",
"sinuiju",
"sunch\u2019on",
"tokch\u2019on",
"wonsan"
],
"kr": [
"ansan-si",
"anyang-si",
"bucheon-si",
"busan",
"changwon",
"cheonan",
"cheongju-si",
"daegu",
"daejeon",
"goyang-si",
"gwangju",
"hwaseong-si",
"incheon",
"jeju city",
"jeonju",
"kimhae",
"korea",
"korea, republic of",
"pohang",
"seongnam-si",
"seoul",
"south korea",
"suwon",
"ulsan"
],
"kw": [
"al ahmadi",
"kuwait",
"kuwait city",
"state of kuwait"
],
"ky": [
"cayman islands",
"george town"
],
"kz": [
"aktobe",
"almaty",
"astana",
"atyrau",
"karagandy",
"kazakhstan",
"kostanay",
"kyzylorda",
"nur-sultan",
"oral",
"pavlodar",
"petropavl",
"republic of kazakhstan",
"semey",
"shymkent",
"taraz",
"turkestan",
"ust-kamenogorsk"
],
"la": [
"lao people's democratic republic",
"laos",
"vientiane"
],
"lb": [
"beirut",
"lebanese republic",
"lebanon",
"ra\u2019s bayrut"
],
"lc": [
"castries",
"saint lucia"
],
"li": [
"liechtenstein",
"principality of liechtenstein",
"vaduz"
],
"lk": [
"colombo",
"dehiwala-mount lavinia",
"democratic socialist republic of sri lanka",
"sri lanka"
],
"lr": [
"liberia",
"monrovia",
"republic of liberia"
],
"ls": [
"kingdom of lesotho",
"lesotho",
"maseru"
],
"lt": [
"kaunas",
"lithuania",
"republic of lithuania",
"vilnius"
],
"lu": [
"grand duchy of luxembourg",
"luxembourg"
],
"lv": [
"latvia",
"republic of latvia",
"riga"
],
"ly": [
"al khums",
"az zawiyah",
"benghazi",
"libya",
"misratah",
"tripoli",
"zliten"
],
"ma": [
"agadir",
"al hoceima",
"beni mellal",
"casablanca",
"el jadida",
"kenitra",
"khouribga",
"kingdom of morocco",
"marrakesh",
"meknes",
"mohammedia",
"morocco",
"oujda",
"rabat",
"safi",
"sale",
"sale al jadida",
"tangier",
"temara",
"tetouan"
],
"mc": [
"monaco",
"principality of monaco"
],
"md": [
"chisinau",
"moldova",
"moldova, republic of",
"republic of moldova"
],
"me": [
"montenegro",
"podgorica"
],
"mf": [
"marigot",
"saint martin",
"saint martin (french part)"
],
"mg": [
"antananarivo",
"antsirabe",
"fianarantsoa",
"madagascar",
"mahajanga",
"republic of madagascar",
"toamasina"
],
"mh": [
"majuro",
"marshall islands",
"republic of the marshall islands"
],
"mk": [
"north macedonia",
"republic of north macedonia",
"skopje"
],
"ml": [
"bamako",
"koutiala",
"mali",
"republic of mali",
"segou",
"sikasso"
],
"mm": [
"amarapura",
"bago",
"insein",
"kyain seikgyi township",
"mandalay",
"mawlamyine",
"myanmar",
"nay pyi taw",
"pathein",
"republic of myanmar",
"yangon"
],
"mn": [
"mongolia",
"ulaanbaatar",
"ulan bator"
],
"mo": [
"macao",
"macao special administrative region of china",
"macau"
],
"mp": [
"commonwealth of the northern mariana islands",
"northern mariana islands",
"saipan"
],
"mq": [
"fort-de-france",
"martinique"
],
"mr": [
"islamic republic of mauritania",
"mauritania",
"nouakchott"
],
"ms": [
"montserrat",
"plymouth"
],
"mt": [
"malta",
"republic of malta",
"valletta"
],
"mu": [
"mauritius",
"port louis",
"republic of mauritius"
],
"mv": [
"maldives",
"male",
"republic of maldives"
],
"mw": [
"blantyre",
"lilongwe",
"malawi",
"mzuzu",
"republic of malawi"
],
"mx": [
"chihuahua",
"ciudad juarez",
"ciudad nezahualcoyotl",
"culiacan",
"ecatepec de morelos",
"guadalajara",
"gustavo adolfo madero",
"hermosillo",
"iztapalapa",
"leon de los aldama",
"merida",
"mexicali",
"mexico",
"mexico city",
"monterrey",
"morelia",
"naucalpan de juarez",
"puebla",
"santiago de queretaro",
"tijuana",
"torreon",
"united mexican states",
"zapopan"
],
"my": [
"bukit rahman putra",
"ipoh",
"iskandar puteri",
"johor bahru",
"kampung baru subang",
"kampung larkin lama",
"klang",
"kota bharu",
"kota damansara",
"kota kinabalu",
"kota kuala muda",
"kuala lumpur",
"kuantan",
"malacca",
"malaysia",
"mukim pulai",
"pelentong",
"petaling jaya",
"sandakan",
"selayang baru utara",
"shah alam",
"subang jaya"
],
"mz": [
"beira",
"chimoio",
"lichinga",
"maputo",
"matola",
"mozambique",
"nacala",
"nampula",
"pemba",
"quelimane",
"republic of mozambique",
"tete"
],
"na": [
"namibia",
"republic of namibia",
"windhoek"
],
"nc": [
"new caledonia",
"noumea"
],
"ne": [
"maradi",
"niamey",
"niger",
"republic of the niger",
"zinder"
],
"nf": [
"kingston",
"norfolk island"
],
"ng": [
"abeokuta",
"abuja",
"akure",
"bauchi",
"benin city",
"enugu",
"federal republic of nigeria",
"gombe",
"ibadan",
"ile-ife",
"ilorin",
"kaduna",
"kano",
"katsina",
"lagos",
"maiduguri",
"nigeria",
"onitsha",
"osogbo",
"port harcourt",
"sokoto",
"warri",
"zaria"
],
"ni": [
"managua",
"nicaragua",
"republic of nicaragua"
],
"nl": [
"amsterdam",
"eindhoven",
"groningen",
"holland",
"kingdom of the netherlands",
"netherlands",
"rotterdam",
"the hague",
"the netherlands",
"utrecht"
],
"no": [
"bergen",
"kingdom of norway",
"norway",
"oslo",
"trondheim"
],
"np": [
"bharatpur",
"biratnagar",
"birganj",
"dhangadhi",
"federal democratic republic of nepal",
"kathmandu",
"nepal",
"patan",
"pokhara"
],
"nr": [
"nauru",
"republic of nauru",
"yaren"
],
"nu": [
"alofi",
"niue"
],
"nz": [
"auckland",
"christchurch",
"manukau city",
"new zealand",
"north shore",
"wellington"
],
"om": [
"bawshar",
"muscat",
"oman",
"seeb",
"sultanate of oman"
],
"pa": [
"panama",
"panama city",
"republic of panama",
"san miguelito"
],
"pe": [
"arequipa",
"cajamarca",
"callao",
"chiclayo",
"chimbote",
"cusco",
"huancayo",
"iquitos",
"juliaca",
"lima",
"peru",
"piura",
"pucallpa",
"republic of peru",
"santiago de surco",
"tacna",
"trujillo"
],
"pf": [
"french polynesia",
"papeete"
],
"pg": [
"independent state of papua new guinea",
"papua new guinea",
"port moresby"
],
"ph": [
"antipolo",
"bacolod city",
"budta",
"cagayan de oro",
"calamba",
"caloocan city",
"cebu city",
"davao",
"general santos",
"iloilo",
"las pinas",
"makati city",
"malingao",
"manila",
"mansilingan",
"paranaque city",
"pasig city",
"philippines",
"quezon city",
"republic of the philippines",
"taguig",
"valenzuela",
"zamboanga"
],
"pk": [
"bahawalpur",
"bannu",
"battagram",
"dera ismail khan",
"faisalabad",
"gujranwala",
"gujrat",
"islamabad",
"islamic republic of pakistan",
"karachi",
"kotli",
"lahore",
"multan",
"muzaffarabad",
"pakistan",
"peshawar",
"quetta",
"rawalpindi",
"sahiwal",
"sargodha",
"shekhupura",
"sialkot",
"sukkur"
],
"pl": [
"bia\u0142ystok",
"bydgoszcz",
"czestochowa",
"gdansk",
"gdynia",
"katowice",
"kielce",
"krakow",
"lublin",
"mokotow",
"poland",
"poznan",
"radom",
"republic of poland",
"sosnowiec",
"szczecin",
"warsaw",
"wroc\u0142aw",
"\u0142odz"
],
"pm": [
"saint pierre and miquelon",
"saint-pierre"
],
"pn": [
"adamstown",
"pitcairn"
],
"pr": [
"bayamon",
"puerto rico",
"san juan"
],
"ps": [
"east jerusalem",
"gaza",
"palestine, state of",
"palestinian territory",
"the state of palestine"
],
"pt": [
"lisbon",
"porto",
"portugal",
"portuguese republic"
],
"pw": [
"melekeok",
"palau",
"republic of palau"
],
"py": [
"asuncion",
"ciudad del este",
"paraguay",
"republic of paraguay",
"san lorenzo"
],
"qa": [
"ar rayyan",
"doha",
"qatar",
"state of qatar"
],
"re": [
"reunion",
"saint-denis"
],
"ro": [
"brasov",
"bucharest",
"cluj-napoca",
"constanta",
"craiova",
"galati",
"iasi",
"romania",
"sector 1",
"sector 2",
"sector 3",
"sector 4",
"sector 5",
"sector 6",
"targu mures",
"timisoara"
],
"rs": [
"belgrade",
"novi sad",
"republic of serbia",
"serbia"
],
"ru": [
"barnaul",
"chelyabinsk",
"izhevsk",
"kazan",
"krasnodar",
"krasnoyarsk",
"moscow",
"nizhniy novgorod",
"novosibirsk",
"omsk",
"perm",
"rostov-na-donu",
"russia",
"russian federation",
"saint petersburg",
"samara",
"saratov",
"tolyatti",
"tyumen",
"ulyanovsk",
"volgograd",
"voronezh",
"yekaterinburg"
],
"rw": [
"kigali",
"rwanda",
"rwandese republic"
],
"sa": [
"abha",
"al hufuf",
"al jubayl",
"al kharj",
"al mubarraz",
"buraydah",
"dammam",
"ha'il",
"hafar al-batin",
"jeddah",
"khamis mushait",
"kingdom of saudi arabia",
"madinah",
"makkah",
"najran",
"riyadh",
"saudi arabia",
"sultanah",
"tabuk",
"ta\u2019if",
"thuqbah",
"yanbu"
],
"sb": [
"honiara",
"solomon islands"
],
"sc": [
"republic of seychelles",
"seychelles",
"victoria"
],
"sd": [
"al qadarif",
"el daein",
"el fasher",
"el obeid",
"kassala",
"khartoum",
"khartoum north",
"kosti",
"nyala",
"omdurman",
"port sudan",
"republic of the sudan",
"singa",
"sudan",
"wad medani"
],
"se": [
"goteborg",
"kingdom of sweden",
"malmo",
"stockholm",
"sweden"
],
"sg": [
"bedok new town",
"hougang new town",
"jurong town",
"jurong west",
"republic of singapore",
"sengkang new town",
"singapore",
"tampines estate",
"tampines new town",
"ulu bedok",
"woodlands",
"yishun new town"
],
"sh": [
"jamestown",
"saint helena",
"saint helena, ascension and tristan da cunha"
],
"si": [
"ljubljana",
"republic of slovenia",
"slovenia"
],
"sj": [
"longyearbyen",
"svalbard and jan mayen"
],
"sk": [
"bratislava",
"kosice",
"slovak republic",
"slovakia"
],
"sl": [
"freetown",
"republic of sierra leone",
"sierra leone"
],
"sm": [
"republic of san marino",
"san marino"
],
"sn": [
"dakar",
"guediawaye",
"kaolack",
"mbour",
"pikine",
"republic of senegal",
"rufisque",
"rufisque est",
"saint-louis",
"senegal",
"thies",
"thies nones",
"touba",
"ziguinchor"
],
"so": [
"berbera",
"borama",
"federal republic of somalia",
"hargeysa",
"kismayo",
"marka",
"mogadishu",
"somalia"
],
"sr": [
"paramaribo",
"republic of suriname",
"suriname"
],
"ss": [
"juba",
"republic of south sudan",
"south sudan",
"winejok"
],
"st": [
"democratic republic of sao tome and principe",
"sao tome",
"sao tome and principe"
],
"sv": [
"el salvador",
"republic of el salvador",
"san miguel",
"san salvador",
"soyapango"
],
"sx": [
"philipsburg",
"sint maarten",
"sint maarten (dutch part)"
],
"sy": [
"al hasakah",
"aleppo",
"ar raqqah",
"damascus",
"deir ez-zor",
"hamah",
"homs",
"latakia",
"syria",
"syrian arab republic",
"tartus"
],
"sz": [
"eswatini",
"kingdom of eswatini",
"mbabane"
],
"tc": [
"cockburn town",
"turks and caicos islands"
],
"td": [
"chad",
"n'djamena",
"republic of chad"
],
"tf": [
"french southern territories",
"port-aux-francais"
],
"tg": [
"lome",
"togo",
"togolese republic"
],
"th": [
"bangkok",
"chon buri",
"kingdom of thailand",
"mueang nonthaburi",
"samut prakan",
"thailand"
],
"tj": [
"dushanbe",
"isfara",
"istaravshan",
"konibodom",
"kulob",
"republic of tajikistan",
"tajikistan"
],
"tk": [
"tokelau"
],
"tl": [
"democratic republic of timor-leste",
"dili",
"timor leste",
"timor-leste"
],
"tm": [
"ashgabat",
"turkmenabat",
"turkmenistan"
],
"tn": [
"republic of tunisia",
"sfax",
"sousse",
"tunis",
"tunisia"
],
"to": [
"kingdom of tonga",
"nuku'alofa",
"tonga"
],
"tr": [
"adana",
"ankara",
"antalya",
"bagc\u0131lar",
"bahcelievler",
"bursa",
"cankaya",
"diyarbak\u0131r",
"erzurum",
"esenler",
"eskisehir",
"gaziantep",
"istanbul",
"izmir",
"karabaglar",
"kayseri",
"konya",
"malatya",
"mersin",
"republic of turkiye",
"turkey",
"turkiye",
"umraniye",
"uskudar"
],
"tt": [
"port of spain",
"republic of trinidad and tobago",
"trinidad and tobago"
],
"tv": [
"funafuti",
"tuvalu"
],
"tw": [
"bade",
"banqiao",
"chang-hua",
"changhua",
"chiayi city",
"fengshan",
"hsinchu",
"kaohsiung",
"keelung",
"neihu",
"new taipei city",
"taichung",
"tainan",
"taipei",
"taiwan",
"taiwan, province of china",
"taoyuan",
"taoyuan city",
"xizhi",
"yongkang",
"zhubei"
],
"tz": [
"arusha",
"bariadi",
"dar es salaam",
"dodoma",
"geita",
"ifakara",
"kahama",
"kasulu",
"kibaha",
"kigoma",
"mbeya",
"morogoro",
"moshi",
"mwanza",
"singida",
"songea",
"sumbawanga",
"tabora",
"tanga",
"tanzania",
"tanzania, united republic of",
"tunduma",
"united republic of tanzania",
"zanzibar"
],
"ua": [
"cherkasy",
"chernihiv",
"dnipro",
"donetsk",
"kharkiv",
"kherson",
"khmelnytskyi",
"kryvyy rih",
"kyiv",
"luhansk",
"lviv",
"makiivka",
"mykolayiv",
"odesa",
"poltava",
"saltivka",
"sevastopol",
"simferopol",
"stara darnytsya",
"ukraine",
"vinnytsya",
"zaporizhzhya"
],
"ug": [
"bunamwaya",
"kampala",
"kasangati",
"kira",
"kyengera",
"mbarara",
"nansana",
"republic of uganda",
"uganda"
],
"um": [
"united states minor outlying islands"
],
"us": [
"america",
"austin",
"brooklyn",
"charlotte",
"chicago",
"columbus",
"dallas",
"fort worth",
"houston",
"indianapolis",
"jacksonville",
"los angeles",
"manhattan",
"new york city",
"philadelphia",
"phoenix",
"queens",
"san antonio",
"san diego",
"san jose",
"the bronx",
"u.s.",
"u.s.a.",
"united states",
"united states of america",
"usa",
"washington"
],
"uy": [
"eastern republic of uruguay",
"montevideo",
"uruguay"
],
"uz": [
"andijon",
"bukhara",
"chilanzar",
"fergana",
"marg\u2018ilon",
"namangan",
"nukus",
"qarshi",
"qo\u2018qon",
"republic of uzbekistan",
"samarkand",
"tashkent",
"uzbekistan",
"yunusobod"
],
"va": [
"holy see (vatican city state)",
"vatican",
"vatican city"
],
"vc": [
"kingstown",
"saint vincent and the grenadines"
],
"ve": [
"alto barinas",
"barinas",
"barquisimeto",
"bolivarian republic of venezuela",
"cabimas",
"caracas",
"ciudad bolivar",
"ciudad guayana",
"coro",
"cumana",
"guarenas",
"los teques",
"maracaibo",
"maracay",
"maturin",
"petare",
"puerto la cruz",
"san cristobal",
"santa teresa del tuy",
"turmero",
"valencia",
"valera",
"venezuela",
"venezuela, bolivarian republic of"
],
"vg": [
"british virgin islands",
"road town",
"virgin islands, british"
],
"vi": [
"charlotte amalie",
"u.s. virgin islands",
"virgin islands of the united states",
"virgin islands, u.s."
],
"vn": [
"bac giang",
"bien hoa",
"buon ma thuot",
"can tho",
"cho lon",
"da nang",
"di an",
"haiphong",
"hanoi",
"ho chi minh city",
"nam \u0111inh",
"nha trang",
"qui nhon",
"rach gia",
"socialist republic of viet nam",
"thai nguyen",
"thanh hoa",
"thu \u0111uc",
"thuan an",
"viet nam",
"viet tri",
"vietnam",
"vinh",
"vung tau"
],
"vu": [
"port vila",
"republic of vanuatu",
"vanuatu"
],
"wf": [
"mata utu",
"wallis and futuna"
],
"ws": [
"apia",
"independent state of samoa",
"samoa"
],
"xk": [
"kosovo",
"pristina"
],
"ye": [
"aden",
"al hudaydah",
"mukalla",
"republic of yemen",
"sanaa",
"taiz",
"yemen"
],
"yt": [
"mamoudzou",
"mayotte"
],
"za": [
"benoni",
"bloemfontein",
"boksburg",
"cape town",
"diepsloot",
"durban",
"east london",
"emalahleni",
"evaton",
"johannesburg",
"krugersdorp",
"pietermaritzburg",
"port elizabeth",
"pretoria",
"randburg",
"republic of south africa",
"rustenburg",
"soshanguve",
"south africa",
"soweto",
"thembisa",
"vereeniging",
"welkom"
],
"zm": [
"chingola",
"chipata",
"kabwe",
"kitwe",
"lusaka",
"ndola",
"republic of zambia",
"solwezi",
"zambia"
],
"zw": [
"bulawayo",
"chitungwiza",
"epworth",
"harare",
"mutare",
"republic of zimbabwe",
"zimbabwe"
]
}

ADZUNA_SUPPORTED = set(["at", "au", "be", "br", "ca", "ch", "de", "es", "fr", "gb", "in", "it", "mx", "nl", "nz", "pl", "sg", "us", "za"])

ADZUNA_COUNTRY_LEVEL = set(["america", "amsterdam", "australia", "austria", "belgium", "berlin", "bern", "brasilia", "brazil", "britain", "brussels", "canada", "canberra", "deutschland", "england", "federal republic of germany", "federative republic of brazil", "france", "french republic", "germany", "great britain", "holland", "india", "italian republic", "italy", "kingdom of belgium", "kingdom of spain", "kingdom of the netherlands", "london", "madrid", "mexico", "mexico city", "netherlands", "new delhi", "new zealand", "northern ireland", "ottawa", "paris", "poland", "pretoria", "republic of austria", "republic of india", "republic of poland", "republic of singapore", "republic of south africa", "rome", "scotland", "singapore", "south africa", "spain", "swiss confederation", "switzerland", "the netherlands", "u.k.", "u.s.", "u.s.a.", "uk", "united kingdom", "united kingdom of great britain and northern ireland", "united mexican states", "united states", "united states of america", "usa", "vienna", "wales", "warsaw", "washington", "wellington"])

